[package]
name = "mzdata"
version = "0.4.0"
edition = "2018"
keywords = [
    'mass-spectrometry',
    'mzml',
    'mgf'
]

categories = [
    "science",
    "parser-implementations",
    "data-structures"
]

description = "A library to read mass spectrometry data formats"
license = "Apache-2.0"
repository = "https://github.com/mobiusklein/mzdata"
documentation = "https://docs.rs/mzdata"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "mzdata"
src = "src/main.rs"


[lib]
name = "mzdata"
src = "src/lib.rs"

[profile.release]
lto = true


[features]
default = ["intel-mkl", "parallelism", "zlib"]

openblas = ["mzsignal/openblas"]
netlib = ["mzsignal/netlib"]
intel-mkl = ["mzsignal/intel-mkl"]
parallelism = ["rayon", "mzsignal/parallelism"]

# The zlib feature makes the code faster unoptimized, but with LTO the default
# algorithm is faster on tests. Odds are on real data, this will vary with the
# size of the data being shuttled back and forth, and on the quality of the data
# (de)compression.
zlib = ["flate2/zlib"]
zlib-ng-compat = ["flate2/zlib-ng-compat"]
miniz_oxide = ["flate2/rust_backend"]

[dependencies]
regex = "1"
lazy_static = "1.4.0"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
quick-xml = { version = "0.22", features = [ "serialize" ] }
base64 = "0.13.0"
flate2 = {version = "1.0.20"}
num-traits = "0.2"
indexmap = { version = "1.7.0", features = [ "serde" ] }
log = "0.4.14"
mzpeaks = "0.4.0"
rayon = { version = "1.5.1", optional = true }
mzsignal = { version = "0.2.3", default-features = false}
md5 = "0.7.0"

[dev-dependencies]
criterion = { version = "0.3.4", features = [ "html_reports" ] }

[[bench]]
name = "mzml"
harness = false


[package.metadata.docs.rs]
features = ["openblas", "parallelism"]
no-default-features = true