[package]
name = "structured"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "structured"
src = "src/main.rs"

[lib]
name = "structured"
src = "src/lib.rs"

[dependencies]
