[package]
name = "mzdata"
version = "0.1.0"
edition = "2018"
keywods = [
    'mass spectrometry',
    'mzml',
    'mgf'
]

description = "A library to read mass spectrometry data formats"
license = "Apache2"
repository = "https://github.com/mobiusklein/mzdata"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "mzdata"
src = "src/main.rs"


[lib]
name = "mzdata"
src = "src/lib.rs"

[profile.release]
lto = true

[dependencies]
regex = "1"
lazy_static = "1.4.0"
quick-xml = { version = "0.22", features = [ "serialize" ] }
base64 = "0.13.0"
flate2 = "1.0.20"
num-traits = "0.2"
indexmap = { version = "1.7.0", features = [ "serde" ] }
