[package]
name = "structured"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "structured"
src = "src/main.rs"

[lib]
name = "structured"
src = "src/lib.rs"

[dependencies]
regex = "1"
lazy_static = "1.4.0"
serde = { version = "1.0", features = [ "derive" ] }
quick-xml = { version = "0.22", features = [ "serialize" ] }
base64 = "0.13.0"
flate2 = "1.0.20"
num-traits = "0.2"